### ISSUE TITLE
Error: Cannot find module 'webpack/lib/ConcatSource'

### ISSUE THREAD

**Issue by cherishsantosh** [piratefsh/js-motion-detector#2]
$ webpack-dev-server --inline  --content-base public/
module.js:472
    throw err;
    ^

Error: Cannot find module 'webpack/lib/ConcatSource'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/kms/Desktop/js-motion-detector/node_modules/extract-text-webpack-plugin/index.js:5:20)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by anekpattanakij** [comment]
What's your version for extract-text-webpack-plugin and webpack?
I think one of those library is outdated.

**Comment by ananddodia** [comment]
same error shown when i build with webpack-prod-config.

**Comment by piratefsh** [comment]
what versions of `webpack` and `extract-text-webpack` are y'all using? it is building for me on webpack@1.15.0 and extract-text-webpack-plugin@0.8.2. 

It's outdated kinda but this project is not actively maintained.

**Comment by ananddodia** [comment]
Webpack 2.2.0 and extract-text-webpack-plugin 0.9.1

**Comment by piratefsh** [comment]
The config for this does not support Webpack 2. Will gladly accept a PR to
fix this :) Sorry I can't be of more help.

Please try with Webpack 1.15.0 if you just want to get this running.
